import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TRPCProvider from "./_trpc/providor";
import "@uploadthing/react/styles.css";
import { Toaster } from "@/components/ui/toaster";
import Nav from "@/components/Nav";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TRPCProvider>
        <body className="w-screen h-screen">
          {children}
          <Toaster />
        </body>
      </TRPCProvider>
    </html>
  );
}
